on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Printing Folder Content'
        run: ls
      
      - uses: actions/checkout@v3

      - name: 'Printing Folder Content'
        run: ls