on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login in docker hub"
        run: docker login --username ${{ m2mena7med }} --password ${{ m2mena7med }}

      - name: "Bulding docker image"
        run: docker build -t ${{ m2mena7med }}/myimage .
      
      - name: "Pushing to Docker hub"
        run: docker push ${{ m2mena7med }}/myimage .
